-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "clientAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "supplierAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "OrderItem" ADD COLUMN     "supplierUnitPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "supplierPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
